server:
  port: 8083

spring:
  profiles:
    active: auth
  application:
    name: auth-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/